### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Gods-good** [joelcho/chia-rpc-java#1]
能给个联系方式吗  或者加我一下，想请假个问题。 源码拷下来后，跑不通。

**Comment by joelcho** [comment]
你好，如需要帮助，请贴出详细的错误

**Comment by Gods-good** [comment]
![image](https://user-images.githubusercontent.com/39650584/120421260-8c3a2c00-c398-11eb-9040-f3e224aab248.png)

**Comment by joelcho** [comment]
你使用的 chia 钱包节点和我开发的时候的版本不一样。在你这个版本中该API 添加了一些字段，导致json反序列化失败了。

我目前没有时间来修改这个项目。如果你需要使用，请自行修复。

欢迎PR
