### ISSUE TITLE
关于puzzleHash

### ISSUE THREAD

**Issue by ruiyeclub** [joelcho/chia-rpc-java#4]
老哥 我想要通过离线方式生成xch钱包地址 公钥到puzzleHash这步没找到合适的方法

**Comment by joelcho** [comment]
也许这个库能解决你的问题: [herumi/mcl](https://github.com/herumi/mcl)

最近我有点忙，并且我目前的工作内容和Chia不相关。

**Comment by ruiyeclub** [comment]
好的 感谢
